export class User {

    constructor(
        public userid?: number,  // will be autogenerated
        public username?: String,  // this is infact the email address user will enter on the website screen
        public name?: String,
        public location?: String,
        public photo?: any,
        public resume?:any,
        public skills?:any,
        public password?: String,
        public role?: String,
        public education?: String,
        public jobs?:any,
    ) { }

   
}